# WAP to find prime number

In [18]:
x = int(input("enter number : "))
y = 0
if x > 1:
    for i in range(1,int(x/2) + 1) :
        if x % i == 0 : 
            y = y+1
    if y == 1:
        print("number is prime")
    else :
        print("number is non-prime")
else :
    print("Invalid number")
        

enter number : 4
number is non-prime


# Patterns

In [21]:
a = 4
while a > 0:
    print('*' * 4)
    a = a - 1

****
****
****
****


In [23]:
a = 4
while a > 0:
    print('*' * a)
    a = a - 1

****
***
**
*


In [2]:
a = 4
b = 0
while a > 0:
    print(' '*b,'*' * a)
    a = a - 1
    b = b + 1

 ****
  ***
   **
    *


In [5]:
a = 4
b = [1,2,3,4]
while a > 0:
    for i in b:
        print(i,end = ' ')
    print(' ')
    b.pop()
    a = a - 1

1 2 3 4  
1 2 3  
1 2  
1  


In [17]:
a = 4
b = [1,2,3,4]
c = 0
while a > 0:
    print(c*'  ',end = '')
    for i in b:
        print(i,end = ' ')
    print(' ')
    b.pop()
    a = a - 1
    c = c +1

1 2 3 4  
  1 2 3  
    1 2  
      1  


In [8]:
x = 3
a = 1
p = 0
for i in range(1,5):
    print(' '*x,end = '')
    while i > 0:
        print(a,end = ' ')
        a = a +1
        i = i -1
    print('')
    x = x-1
    
    
    

   1 
  2 3 
 4 5 6 
7 8 9 10 


In [30]:
from numpy import *
arr = array([[1,2,3],[4,5,6]])
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
int64
(2, 3)
6
2


In [9]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[1 2 3 4 5]
int64
(5,)
5
1


In [3]:
from numpy import *
arr = array([1,2,3,4,5])
arr = arr + 5
arr2 = array([5,6,7,8])

print(log(arr))
print(id(arr))

[1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
140661088469680


# Props of numpy 

In [5]:
from numpy import *
arr = array([1,2,3,4])

arr3 = arr
arr[1] = 78
print(id(arr3))
print(id(arr))
print(arr3)
print(arr) 

139642395206160
139642395206160
[ 1 78  3  4]
[ 1 78  3  4]


#  Shallow copy

In [6]:
arr3 = arr.view()
print(id(arr3))
print(id(arr))
arr[1] = 9
print(id(arr3))
print(id(arr))
print(arr3)
print(arr) 




139642395206400
139642395206160
139642395206400
139642395206160
[1 9 3 4]
[1 9 3 4]


#  Deep Copy 

In [7]:
arr3 = arr.copy()
print(id(arr3))
print(id(arr))
arr[1] = 13
print(id(arr3))
print(id(arr))
print(arr3)
print(arr) 


139642395206720
139642395206160
139642395206720
139642395206160
[1 9 3 4]
[ 1 13  3  4]


#  2D array

In [14]:
marr = array([[1,2,3,4],[5,6,7,8]])
A1 = marr.flatten()
A2 = marr.reshape(4,2)
A3 = marr.reshape(2,4)
A4 = marr.reshape(2,2,2)
print(A1)
print(A2)
print(A3)
print(A4)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Matrix

In [20]:
m1 = matrix('2,5,4;9,10,8;11,17,19')
m = matrix('1,5,6,7;7,8,9,10')
m2 = matrix('1,5;7,8;4,5;6,3')
m3 = matrix('1,2,3,4;7,8,9,4')
print('m: ',m)
print('Max : ',m.max())
print('Diagonal : ', m.diagonal())

print(m*m2)
print(m + m3)


m:  [[ 1  5  6  7]
 [ 7  8  9 10]]
Max :  10
Diagonal :  [[1 8]]
[[102  96]
 [159 174]]
[[ 2  7  9 11]
 [14 16 18 14]]


#  WAP to sort an array in asending order

In [24]:
arr = array([4,1,2,6])
for i in range(0,len(arr)) :
    for j in range(i+1,len(arr)):
        if arr[i] > arr[j]:
            arr[i],arr[j] = arr[j],arr[i]
for i in arr:
    print(i,end = ' ')

1 2 4 6 

## WAP to check a number as panidrome

In [29]:
x = int(input("Enter a number : "))
n = x
r = 0

while n > 0 :
    d = n % 10
    r = r*10 + d
    n = int(n/10)
if x == r :
    print("Number is panidrome")
else : 
    print("number is not panindrome")

Enter a number : 456
number is not panindrome


## WAP to find fectorical of a given number

In [31]:
x = int(input("Enter a number : "))
fect = 1
while x > 0:
    fect *= x
    x -= 1
    
print(fect)

Enter a number : 0
1


## Creat an array with 5 value and delete array the value at   3 without inbuilt function

In [20]:
from array import *
n = int(input("Enter array length : "))
arr = array('i',[])
print("Enter ELEMENT : ")
for i in range(0,n):
    x = int(input())
    arr.append(x)
d = int(input("Enter index: "))
for i in range(d,n-1):
    arr[i] = arr[i + 1]
n -=1
for i in range(0,n):
    print(arr[i],end = ' ')
    

Enter array length : 6
Enter ELEMENT : 
1
2
3
4
5
6
Enter index: 3
1 2 3 5 6 

## WAP to reverse an array without using inbuilt function fxn

In [22]:
n = int(input("Enter array length : "))
arr = array('i',[])
print("Enter ELEMENT : ")
for i in range(0,n):
    x = int(input())
    arr.append(x)
print("Array : ")
for i in range(0,n):
    print(arr[i],end = ' ')
print("\nReverse Array : ")
for i in range(0,n):
    print(arr[n-1-i],end = ' ')



Enter array length : 6
Enter ELEMENT : 
1
2
3
4
5
6
Array : 
1 2 3 4 5 6 
Reverse Array : 
6 5 4 3 2 1 

## WAP to add two array using for loop

In [24]:
from numpy import *
arr = array([[1,2,3],[4,5,6]])
arr1 = array([[11,12,13],[14,15,16]])
add = array([[0,0,0],[0,0,0]])
for i in range(0,len(arr)):
    for j in range(0,len(arr[i])):
        add[i][j] = arr[i][j] + arr1[i][j]

print(add)
        
    

[[12 14 16]
 [18 20 22]]


## wap to find max value of array

In [25]:
arr = array([4,7,8,9,6,2,55,47])
max = 0
for i in arr :
    if i > max:
        max = i
print("max : ", max)

max :  55


## WAP to multiple two matrix using 2D array and loop 

In [ ]:
from numpy import *
arr = array([[1,2,3],[4,5,6]])
arr1 = array([[11,12,13],[14,15,16],[1,1,1]])
add = array([[0,0,0],[0,0,0]])
for i in range(0,len(arr)):
    for j in range(0,len(arr[i])):
        add[i][j] = arr[i][j] + arr1[i][j]

print(add)
        